app/models.py
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from flask import current_app
from app import db, login


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, HiddenField, IntegerField, SelectField, DecimalField, TextAreaField
from wtforms.fields.html5 import DateTimeField, DateField
from wtforms.validators import DataRequired, ValidationError, Email, EqualTo, Optional, Length, InputRequired
from app.models import Location, Game


class CreateLocation(FlaskForm):
	user_id = HiddenField('user_id')
	location_name = StringField('Location Name', validators=[DataRequired()])
	submit = SubmitField('Create Location')

	def validate_location_name(self, location_name):
		location = Location.query.filter_by(user_id = self.user_id.data, name = self.location_name.data).first()
		if location is not None:
			raise ValidationError('Location with this name already exists')


class CreateGame(FlaskForm):
	user_id = HiddenField('user_id')
	format = SelectField('Game Format', choices=[('Hold''em','Hold''em'), ('Omaha','Omaha'), ('7-card Stud','7-card Stud')])
	limit = SelectField('Limit Type', choices = [('No-limit','No-limit'), ('Pot-Limit','Pot-limit'), ('Fixed Limit','Fixed Limit')])
	small_blind = IntegerField('Small Blind', validators = [DataRequired()])
	big_blind = IntegerField('Big Blind', validators = [DataRequired()])
	straddle = IntegerField('Straddle')
	ante = IntegerField('Ante')
	submit = SubmitField('Create Game Type')


class CreateSession(FlaskForm):
	user_id = HiddenField('user_id')
	buy_in = IntegerField('Buy-in', validators = [DataRequired()])
	cash_out = IntegerField('Cashout', validators = [InputRequired()])
	date = DateField('Start Time', validators = [DataRequired()])
	duration = DecimalField('Duration', validators = [DataRequired()])
	location = SelectField('Session Location', coerce = int, validators = [DataRequired()])
	game_type = SelectField('Session Game Type', coerce = int, validators = [DataRequired()])
	submit = SubmitField('Create Session')


class DashboardFilters(FlaskForm):
	user_id = HiddenField('user_id')
	start_date = DateField('Start Date', validators = [Optional()])
	end_date = DateField('End Date', validators = [Optional()])
	location = SelectField('Location', coerce = int, validators = [Optional()])
	game_type = SelectField('Game Type', coerce = int, validators = [Optional()])
	submit = SubmitField('Report')

	def validate_end_date(self, end_date):
		if self.start_date.data and self.end_date.data:
			if self.start_date.data > end_date.data:
				raise ValidationError('End date is before start date')


class CreateNote(FlaskForm):
	user_id = HiddenField('user_id')
	date = DateField('Date', validators = [DataRequired()])
	subject = StringField('Subject', validators = [DataRequired(), Length(max = 50)])
	note_text = TextAreaField('Note Text', render_kw={'class': 'form-control', 'rows': 7}, validators = [DataRequired(), Length(max = 500)])
	submit = SubmitField('Save')


class CreatePlayer(FlaskForm):
	user_id = HiddenField('user_id')
	first_name = StringField('First Name', validators = [DataRequired(), Length(max = 50)])
	last_name = StringField('Last Name', validators = [Length(max = 50)])
	nick_name = StringField('Nick Name', validators = [Length(max = 50)])
	bio = TextAreaField('Player Bio', validators = [DataRequired(), Length(max = 500)])
	submit = SubmitField('Save')

app/__init__.py
import logging
from logging.handlers import RotatingFileHandler
import os
from flask import Flask, request, current_app
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_bootstrap import Bootstrap


db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
bootstrap = Bootstrap()
login.login_view = 'auth.login'


def create_app(config_class=Config):
	app = Flask(__name__)
	app.config.from_object(config_class)

	db.init_app(app)
	migrate.init_app(app, db)
	login.init_app(app)
	bootstrap.init_app(app)

	from app.auth import bp as auth_bp
	app.register_blueprint(auth_bp, url_prefix = '/auth')

	from app.main import bp as main_bp
	app.register_blueprint(main_bp)

	if app.config['LOG_TO_STDOUT']:
		stream_handler = logging.StreamHandler()
		stream_handler.setLevel(logging.INFO)
		app.logger.addHandler(stream_handler)
	else:
		if not os.path.exists('logs'):
			os.mkdir('logs')
		# CHANGE TO PROJECT NAME
		file_handler = RotatingFileHandler('logs/project_template.log',
										   maxBytes=10240, backupCount=10)
		file_handler.setFormatter(logging.Formatter(
			'%(asctime)s %(levelname)s: %(message)s '
			'[in %(pathname)s:%(lineno)d]'))
		file_handler.setLevel(logging.INFO)
		app.logger.addHandler(file_handler)

	app.logger.setLevel(logging.INFO)
	# CHANGE TO PROJECT NAME
	app.logger.info('Project Template startup')

	return app

from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from app import db
# from app.main.forms import [list forms here]
from app.models import User
from app.main import bp

@bp.route('/')
@bp.route('/index')
@login_required
def index():
	return render_template('index.html')

app/templates/base.html
{% extends 'bootstrap/base.html' %}


{% block title %}
    {% if title %} {{ title }} - Project_Template
    {% else %} Project_Template
    {% endif %}
{% endblock %}

{% block head %}
  {{ super() }}
  <link type="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
{% endblock %}

{% block navbar %}
	<nav class="navbar navbar-default">
	        <div class="container">
	            <div class="navbar-header">
	                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	                    <span class="sr-only">Toggle navigation</span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                </button>
	                <a class="navbar-brand" href="{{ url_for('main.index') }}">Project_Template</a>
	            </div>
	            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	                <ul class="nav navbar-nav">
	        			<li><a href="{{ url_for('main.index') }}">Home</a></li>
		        			  {% if current_user.is_anonymous %}
					        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
					        {% else %}
					        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
					        {% endif %}
        				</ul>
	    		</div>
    		</div>
		</nav>
{% endblock %}


{% block content %}
	<div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
    	{% block app_content %}{% endblock %}
    </div>


{% endblock %}

{% block scripts %}
  {{ super() }}
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
  <script type="text/javascript">
    $(function () {
      $('#datepick').datetimepicker();
    });
  </script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}

<h3>Welcome to Project Template!</h3>

{% endblock %}